// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Confirmation struct {
	ID            int64
	UserID        int64
	ConfirmedName string
}

type Session struct {
	ID        int64
	Token     string
	ExpiresAt int64
	UserID    int64
	Foreign   interface{}
}

type Token struct {
	Token     string
	ExpiresAt int64
	UserID    int64
	TokenType string
}

type User struct {
	ID            int64
	Name          string
	Slug          string
	ReservedSpots int64
}
