// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const getToken = `-- name: GetToken :one
SELECT token, expires_at, user_id, token_type FROM tokens
WHERE token = ? LIMIT 1
`

func (q *Queries) GetToken(ctx context.Context, token string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getToken, token)
	var i Token
	err := row.Scan(
		&i.Token,
		&i.ExpiresAt,
		&i.UserID,
		&i.TokenType,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, slug, reserved_spots FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ReservedSpots,
	)
	return i, err
}
